Document: yandex-mongo-cxx-driver
Title: Debian yandex-mongo-cxx-driver Manual
Author: <insert document author here>
Abstract: This manual describes what yandex-mongo-cxx-driver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yandex-mongo-cxx-driver/yandex-mongo-cxx-driver.sgml.gz

Format: postscript
Files: /usr/share/doc/yandex-mongo-cxx-driver/yandex-mongo-cxx-driver.ps.gz

Format: text
Files: /usr/share/doc/yandex-mongo-cxx-driver/yandex-mongo-cxx-driver.text.gz

Format: HTML
Index: /usr/share/doc/yandex-mongo-cxx-driver/html/index.html
Files: /usr/share/doc/yandex-mongo-cxx-driver/html/*.html
